### ISSUE TITLE
Cannot load such file -- timetrap

### ISSUE THREAD

**Issue by csolg** [samg/timetrap#125]
Hi!

When I run in command line 'timetrap' then the error occurs:

```
cannot load such file -- timetrap: ["/home/csolg/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'", "/home/csolg/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'", "/home/csolg/.rvm/gems/ruby-2.2.4/gems/timetrap-1.10.0/bin/timetrap:3:in `<top (required)>'", "/home/csolg/.rvm/gems/ruby-2.2.4/bin/timetrap:22:in `load'", "/home/csolg/.rvm/gems/ruby-2.2.4/bin/timetrap:22:in `<main>'", "/home/csolg/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'", "/home/csolg/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'"]
```
Ruby version is 2.2.4.
Thanks.

**Comment by lieuwex** [comment]
Same issue here
```
$ timetrap
cannot load such file -- timetrap: ["/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'", "/usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'", "/usr/local/lib/ruby/gems/2.3.0/gems/timetrap-1.10.0/bin/timetrap:3:in `<top (required)>'", "/usr/local/bin/timetrap:22:in `load'", "/usr/local/bin/timetrap:22:in `<main>'"]
```

**Comment by csolg** [comment]
I reinstalled ruby from 2.2.4 to 2.3.0. Now it works.

**Comment by JoshRosso** [comment]
Similarly, I didn't realize after updating to 2.3.0, `gem uninstall timetrap` was not removing the old entries from `/usr/bin`. After removing `t` and `timetrap` manually then reinstalling timetrap, works great!
