### ISSUE TITLE
timetrap broken after latest mac update

### ISSUE THREAD

**Issue by chadams** [samg/timetrap#213]
```
chadams:~ chadams$ timetrap --help
Traceback (most recent call last):
	8: from /usr/local/bin/timetrap:23:in `<main>'
	7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:303:in `activate_bin_path'
	6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:303:in `synchronize'
	5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems.rb:304:in `block in activate_bin_path'
	4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1420:in `activate'
	3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `activate_dependencies'
	2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1438:in `each'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/specification.rb:1449:in `block in activate_dependencies'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'sqlite3' (~> 1.4.2) - did find: [sqlite3-1.3.13] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/Users/chadams/.gem/ruby/2.6.0:/Library/Ruby/Gems/2.6.0:/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0', execute `gem env` for more information
```

**Comment by categulario** [comment]
I think this is a problem every once in a while...

**Comment by chadams** [comment]
looks like after latest mac update something got borked with pre-installed ruby. I was able to fix my `brew install ruby` and then modifying my .bash_profile to include `export PATH="/usr/local/lib/ruby/gems/3.1.0/bin:$PATH"`
